/**
 * Report writer: one JSON snapshot per run under docs/evidence/loadtest/ and a Markdown
 * run section prepended inside marker comments in docs/evidence/loadtest.md, so the
 * hand-written text around the markers (commands, recommendation) survives reruns.
 */
import type { Summary } from './stats';

export interface RunMeta {
  startedAt: string;
  chainId: number;
  chainName: string;
  rpc: string;
  ws: string;
  address: string;
  sessionId: string;
  wallets: number;
  hitsPerWallet: number;
  windowMs: number;
  rps: number;
  blockMs: number;
  measuredBlockMs: number | null;
  lagBlocks: number;
  note?: string;
}

export interface MemoryFs {
  readFile(path: string): string | null;
  writeFile(path: string, content: string): void;
  mkdir(path: string): void;
}

export const RUNS_START = '<!-- loadtest:runs:start -->';
export const RUNS_END = '<!-- loadtest:runs:end -->';

function ms(v: number | null): string {
  return v === null ? 'n/a' : `${Math.round(v)} ms`;
}

function pct(v: number): string {
  return `${(v * 100).toFixed(1)}%`;
}

export function renderRunSection(meta: RunMeta, s: Summary): string {
  const lines: string[] = [];
  lines.push(`### ${meta.startedAt} · ${meta.chainName} (${meta.chainId})`);
  lines.push('');
  lines.push(`- Target: ${meta.wallets} wallets × ${meta.hitsPerWallet} hits = ${meta.wallets * meta.hitsPerWallet} hits over a ${meta.windowMs} ms window at ${meta.rps} rps (token bucket).`);
  lines.push(`- Contract ${meta.address}, session ${meta.sessionId}, RPC ${meta.rpc}, WS ${meta.ws}.`);
  lines.push(`- Block cadence: nominal ${meta.blockMs} ms, measured ${meta.measuredBlockMs === null ? 'n/a' : `${Math.round(meta.measuredBlockMs)} ms`}; prediction lag ${meta.lagBlocks} block(s).`);
  if (meta.note) lines.push(`- Note: ${meta.note}`);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Hits sent / confirmed / reverted / send-failed / timed out | ${s.hits.total} / ${s.hits.confirmed} / ${s.hits.reverted} / ${s.hits.sendFailed} / ${s.hits.timedOut} |`);
  lines.push(`| Confirmation latency | p50 ${ms(s.latencyMs.p50)} · p95 ${ms(s.latencyMs.p95)} · p99 ${ms(s.latencyMs.p99)} · min ${ms(s.latencyMs.min)} · max ${ms(s.latencyMs.max)} · mean ${ms(s.latencyMs.mean)} |`);
  const landed = s.landing.onTime + s.landing.oneLate + s.landing.late + s.landing.early;
  lines.push(`| Landing vs predicted step | on time ${s.landing.onTime}/${landed} (${pct(s.landing.onTimeRatio)}) · one step late ${s.landing.oneLate} · later ${s.landing.late} · early ${s.landing.early} · within one step ${pct(s.landing.withinOneStepRatio)} |`);
  lines.push(`| Throughput | ${s.confirmedPerSecond.toFixed(2)} confirmed hits/s over ${(s.durationMs / 1000).toFixed(1)} s |`);
  lines.push(`| Rate-limit hits | ${s.rateLimitHits} |`);
  lines.push(`| Token bucket (funding + hit phase) | ${s.bucket.waits} waits, ${s.bucket.waitedMs} ms total wait |`);
  lines.push(`| MON | funded ${s.mon.funded} · funder spent ${s.mon.funderSpent} · hits cost ${s.mon.hitsSpent} · gas used ${s.mon.gasUsedTotal} |`);
  lines.push('');
  lines.push(`Rate-limit hits: ${s.rateLimitHits}. RPC errors:`);
  lines.push('');
  lines.push(`| Code | Count | Rate limit | Sample |`);
  lines.push(`| --- | --- | --- | --- |`);
  if (s.errors.length === 0) lines.push(`| (none) | 0 | no | |`);
  for (const e of s.errors) lines.push(`| ${e.code} | ${e.count} | ${e.rateLimited ? 'yes' : 'no'} | ${e.sample.replace(/\|/g, '\\|').replace(/\s+/g, ' ').slice(0, 120)} |`);
  lines.push('');
  return lines.join('\n');
}

export function upsertRunsSection(existing: string | null, runMarkdown: string, defaultHeader: string): string {
  const block = `${RUNS_START}\n${runMarkdown.trimEnd()}\n`;
  if (existing === null) {
    return `${defaultHeader.trimEnd()}\n\n## Runs (newest first)\n\n${block}${RUNS_END}\n`;
  }
  const start = existing.indexOf(RUNS_START);
  const end = existing.indexOf(RUNS_END);
  if (start === -1 || end === -1 || end < start) {
    return `${existing.trimEnd()}\n\n## Runs (newest first)\n\n${block}${RUNS_END}\n`;
  }
  const previousRuns = existing.slice(start + RUNS_START.length, end).replace(/^\n+/, '');
  return `${existing.slice(0, start)}${block}\n${previousRuns}${existing.slice(end)}`;
}

export const DEFAULT_HEADER = `# Load test evidence

Generated by \`pnpm --filter scripts loadtest\`. Each run adds a section below and a JSON
snapshot in \`docs/evidence/loadtest/\`.`;

export interface WriteReportInput {
  meta: RunMeta;
  summary: Summary;
  evidenceDir: string;
  markdownPath: string;
  fs: MemoryFs;
  /** Extra data to keep in the JSON snapshot (per-hit records, for example). */
  extra?: Record<string, unknown>;
  header?: string;
  /** Applied to the final JSON and Markdown text before writing (secret redaction). */
  scrub?: (text: string) => string;
}

function jsonReplacer(_key: string, value: unknown): unknown {
  return typeof value === 'bigint' ? value.toString() : value;
}

export function writeReport(input: WriteReportInput): { jsonPath: string; markdownPath: string } {
  const stamp = input.meta.startedAt.replace(/[:.]/g, '-');
  const jsonPath = `${input.evidenceDir}/${stamp}.json`;
  input.fs.mkdir(input.evidenceDir);
  const scrub = input.scrub ?? ((t: string) => t);
  input.fs.writeFile(jsonPath, scrub(JSON.stringify({ meta: input.meta, summary: input.summary, ...(input.extra ?? {}) }, jsonReplacer, 2) + '\n'));
  const existing = input.fs.readFile(input.markdownPath);
  const md = upsertRunsSection(existing, scrub(renderRunSection(input.meta, input.summary)), input.header ?? DEFAULT_HEADER);
  input.fs.writeFile(input.markdownPath, md);
  return { jsonPath, markdownPath: input.markdownPath };
}
